### PR TITLE
Fixes cue delay for animation

### PR DESCRIPTION
**Pull request by itf**
50 + params.animate ? params.animationDuration : 0; evaluates to either 0 or param.animationDuration.
50 + (params.animate ? params.animationDuration : 0); was probably what was intended

### CODE REVIEW

**Comment by msalihaltun** [comment]
@itf You are right and the change is correct, but please open a pull request on `unstable` branch since we do development there - and close this one.

**Comment by msalihaltun** [comment]
@itf Additionally, you need to run the `gulp` scripts to build this extension when you make changes to the source files.

**Comment by favorable-mutation** [comment]
See #113 for a version of this PR off of `unstable` and with `gulp build` run on it.

**Comment by msalihaltun** [comment]
#113 has been merged.

**Pull request closed without merging**
