### PR TITLE
Fixed Multiple Tabs Issue

### PR DESCRIPTION
**Pull request by abeersaqib**
Added Z-Index as well

### CODE REVIEW

**Comment by metincansiper** [comment]
@abeersaqib Thanks for your effort. It seems logical to listen ```cy.on('resize', function(){``` instead of  ```$(window).bind('resize', function () {``` to me. I asked Max if there is any  inconvenience of this change. Please see my comment in #23. 

In this extension we build ```cytoscape-expand-collapse.js``` automatically from the source files (by running ```gulp build``` command). Therefore, we need to make the changes in source files instead of  ```cytoscape-expand-collapse.js``` and then build that file.

I think that in your commit, named as 'Fix of Issue-23', the main change is 'https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/pull/24/commits/9e200fc632ca9471d00f64fe31a00d1f894f3324#diff-3fb9b12b337f91715905334068592531R81'. However, do we need the other changes there? Does your problem reappear when  you undo the other changes in that commit.

**Comment by abeersaqib** [comment]
Yes we need the other changes since when ever there are multiple tabs other canvas become of size 100*100 since our multiple tabs are the instances of our desktop based application so window.resize wont trigger for us what triggering for us is the cy.resize due to layout resizing

**Comment by metincansiper** [comment]
@abeersaqib OK, I understand why we need to call sizeCanvas() on cy.resize event. However, what I mean by other changes are 

- The one in the following line 'https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/pull/24/commits/9e200fc632ca9471d00f64fe31a00d1f894f3324#diff-3fb9b12b337f91715905334068592531R43'
I think that we have one canvas instance here which is the varaible '$canvas' and handling it in sizeCanvas() it enough. I could not figure out why we should traverse each of $('.expand-collapse-canvas') instead.

- The other one is the one in the following lines 
https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/pull/24/commits/9e200fc632ca9471d00f64fe31a00d1f894f3324#diff-3fb9b12b337f91715905334068592531R153 and https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/pull/24/commits/9e200fc632ca9471d00f64fe31a00d1f894f3324#diff-3fb9b12b337f91715905334068592531R605. I think that we already have access to cy instance on these functions and do not need to parametrize it.

**Comment by abeersaqib** [comment]
Yeah these lines can be ignored they were the changes made before cy is parametrized

**Comment by abeersaqib** [comment]
@metincansiper I am preparing the jsfiddle it will take some time

**Comment by metincansiper** [comment]
@abeersaqib okey thaks.

**Comment by abeersaqib** [comment]
@metincansiper I've just checked this problem is occurred when we use cytoscape as a Desktop Application 
i am currently using the Electron if i wont add that line the children wont be removed and still clickiable and visible even after the collapse
While on web version the children are removed properly.
if you need the video demo / electron app demo which ever suits you ?

**Comment by kinimesi** [comment]
Implemented in https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/pull/52.

**Pull request closed without merging**
